name: Create Daily GitLab Issues

on:
  schedule:
    - cron: '0 4 * * *' # UTC time 4 AM
  workflow_dispatch:
# Soma: 12121365; Trevor: 19541579; Pedro: 20426172; Herman: 20413440;
jobs:
  create-issues:
    runs-on: ubuntu-latest
    steps:
    - name: Create Trello Check Issue on GitLab
      run: |
      
        curl --request POST --header "PRIVATE-TOKEN: ${{ secrets.GITLAB_ACCESS_TOKEN }}" --data "title=[Auto-created]Trello Check&description=Daily Trello check.&assignee_ids=[20413440,19541579,20426172]&weight=1" "https://gitlab.com/api/v4/projects/55692458/issues"
    - name: Community Bug Report Delegate Issue on GitLab
      run: |
        curl --request POST --header "PRIVATE-TOKEN: ${{ secrets.GITLAB_ACCESS_TOKEN }}" --data "title=[Auto-created]Community Bug Reports Delegate&description=Community Bug Reports Delegate.&assignee_ids=[20426172]&weight=2" "https://gitlab.com/api/v4/projects/55692458/issues"
    - name: Company email check Issue on GitLab
      run: |
        curl --request POST --header "PRIVATE-TOKEN: ${{ secrets.GITLAB_ACCESS_TOKEN }}" --data "title=[Auto-created]Company email check&description=Company email check.&assignee_ids=[19541579]&weight=1" "https://gitlab.com/api/v4/projects/55692458/issues"
